/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.committeEnterprise;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.LegalOfficerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import HomePages.TableFormat;
import java.awt.CardLayout;
import javax.swing.table.DefaultTableModel;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author patol
 */
public class DoctorConsentRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageLegalOfficerRequestJPanel
     */
    private EcoSystem system;
    private UserAccount userAccount;
    private LegalOfficerOrganization legalofficerorganization;
    private Enterprise enterprise;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    
    public DoctorConsentRequestJPanel(EcoSystem system, UserAccount userAccount, LegalOfficerOrganization legalofficerorganization, Enterprise enterprise) {
        initComponents();
        this.system = system;
        this.userAccount = userAccount;
        this.legalofficerorganization = legalofficerorganization;
        this.enterprise = enterprise;
        
        tblPatientData.getTableHeader().setDefaultRenderer(new TableFormat());
        tblassignedRequest.getTableHeader().setDefaultRenderer(new TableFormat());
        populateOrganisationpatientTable();
        populateLegalPatientTable();
        
    }

    public void populateOrganisationpatientTable(){
        DefaultTableModel model = (DefaultTableModel)tblPatientData.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : legalofficerorganization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[6];
            row[0] = request;
            row[1] = request.getSummary();
            row[2] = request.getPatient();
            row[3] = request.getPatient().getName();
            row[4] = request.getPatient().getEmailID();
            row[5] = request.getStatus();
            
            model.addRow(row);
        }
    }
    
  
     public void populateLegalPatientTable(){
        DefaultTableModel model = (DefaultTableModel)tblassignedRequest.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[6];
            row[0] = request;
            row[1] = request.getPatient();
            row[2] = request.getPatient().getName();
            row[3] = request.getPatient().getEmailID();
            row[4] = request.getUserAccount().getUsername();
            row[5] = request.getStatus();
             
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAssign = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPatientData = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblassignedRequest = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabelConsentByDoctor = new javax.swing.JLabel();
        jLabelTo = new javax.swing.JLabel();
        jLabelFrom = new javax.swing.JLabel();
        jLabelSubject = new javax.swing.JLabel();
        jLabelMessage = new javax.swing.JLabel();
        jBtnConsentForm = new javax.swing.JButton();
        TextFieldTo = new javax.swing.JTextField();
        TextFieldFrom = new javax.swing.JTextField();
        TextFieldSubject = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextFieldMessage = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAssign.setBackground(new java.awt.Color(31, 31, 31));
        btnAssign.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnAssign.setForeground(new java.awt.Color(255, 255, 255));
        btnAssign.setText("Assign");
        btnAssign.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 140, 40));

        tblPatientData.setBackground(new java.awt.Color(0, 0, 0));
        tblPatientData.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        tblPatientData.setForeground(new java.awt.Color(255, 255, 255));
        tblPatientData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Number", "Summaryof the Patient", "Patient ID", "Patient Name", "Email ID", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPatientData.setGridColor(new java.awt.Color(0, 0, 0));
        tblPatientData.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblPatientData.setRowHeight(30);
        tblPatientData.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tblPatientData);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 1280, 190));

        tblassignedRequest.setBackground(new java.awt.Color(0, 0, 0));
        tblassignedRequest.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        tblassignedRequest.setForeground(new java.awt.Color(255, 255, 255));
        tblassignedRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Number", "Patient ID", "Patient Name", "Email ID", "Assigned to", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblassignedRequest.setGridColor(new java.awt.Color(0, 0, 0));
        tblassignedRequest.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblassignedRequest.setRowHeight(30);
        tblassignedRequest.setShowVerticalLines(false);
        jScrollPane4.setViewportView(tblassignedRequest);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 1280, 190));

        jPanel3.setBackground(new java.awt.Color(31, 31, 31));
        jPanel3.setPreferredSize(new java.awt.Dimension(926, 70));

        jLabelConsentByDoctor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelConsentByDoctor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConsentByDoctor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConsentByDoctor.setText("Treatment Consent Request by Doctor");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelConsentByDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 1556, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelConsentByDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, -1));

        jLabelTo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelTo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTo.setText("To:");
        add(jLabelTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, -1, -1));

        jLabelFrom.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelFrom.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFrom.setText("From:");
        add(jLabelFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 600, -1, -1));

        jLabelSubject.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelSubject.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSubject.setText("Subject:");
        add(jLabelSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 640, -1, -1));

        jLabelMessage.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelMessage.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMessage.setText("Message: ");
        add(jLabelMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 700, -1, -1));

        jBtnConsentForm.setBackground(new java.awt.Color(31, 31, 31));
        jBtnConsentForm.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jBtnConsentForm.setForeground(new java.awt.Color(255, 255, 255));
        jBtnConsentForm.setText("Send Consent Form On email");
        jBtnConsentForm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnConsentForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsentFormActionPerformed(evt);
            }
        });
        add(jBtnConsentForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 760, 290, 40));

        TextFieldTo.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldTo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        TextFieldTo.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldToActionPerformed(evt);
            }
        });
        add(TextFieldTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 560, 320, -1));

        TextFieldFrom.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldFrom.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        TextFieldFrom.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldFrom.setText("aedprojecttitans@gmail.com");
        TextFieldFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldFromActionPerformed(evt);
            }
        });
        add(TextFieldFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 600, 320, -1));

        TextFieldSubject.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldSubject.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        TextFieldSubject.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldSubject.setText("Legal Consent");
        add(TextFieldSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 640, 320, -1));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/legal-paper.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, 130, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/letter.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 580, 130, 130));

        TextFieldMessage.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldMessage.setColumns(20);
        TextFieldMessage.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        TextFieldMessage.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldMessage.setRows(5);
        TextFieldMessage.setText("Hello,\n\nGreetings of the Day!\n\nKindly sign the Consent form for Plasma Therapy Treatment.\n\nThank you");
        jScrollPane1.setViewportView(TextFieldMessage);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 710, 330, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
       int selectedRow = tblPatientData.getSelectedRow();
        
        if (selectedRow < 0){
           //JOptionPane.showMessageDialog(null, "Please select a row", "Error", JOptionPane.ERROR_MESSAGE);
           JOptionPane.showMessageDialog(null, new JLabel(  "<html><h2><I>Please select<font color='red'> a row</font> from the<font color='green'> table</I></font></h2></html>"), "Error", JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            WorkRequest request = (WorkRequest)tblPatientData.getValueAt(selectedRow, 0);    
           
            if(request.getStatus().equals("Assigned to Legal Pool"))
            {
            request.setStatus("Assign to LegalOfficer" + userAccount.getUsername());
            request.setUserAccount(userAccount);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
            }
            else{
            //JOptionPane.showMessageDialog(null, "Work Request is already assigned!" );
            JOptionPane.showMessageDialog(null, new JLabel(  "<html><h2><I>Work Request is<font color='red'> already</font> in progress!</I></h2></html>"), "Warning", JOptionPane.WARNING_MESSAGE);
             
            }
            dB4OUtil.storeSystem(system);
            populateOrganisationpatientTable();
            populateLegalPatientTable();
        }
        
    }//GEN-LAST:event_btnAssignActionPerformed

    private void jBtnConsentFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsentFormActionPerformed
        // TODO add your handling code here:

        if(TextFieldTo.getText().equals("") || TextFieldSubject.getText().equals("") ||  TextFieldMessage.getText().equals("")){

            JOptionPane.showMessageDialog(null,new JLabel("<html><h2><I>All fields are</I><font color='red'> mandatory</font>!</h2></html>"), "Error", JOptionPane.ERROR_MESSAGE);
       
            //JOptionPane.showMessageDialog(null, "Please fill all the fields!" );
        }
        else{
        String toEmail = TextFieldTo.getText();
        //       String toEmail = "yashwant7kotipalli@gmail.com";
        //       final String fromEmail = "yashwant7kotipalli@gmail.com";
        final String fromEmail = TextFieldFrom.getText();
        final String fromEmailPassword = "teamtitans"; //your email password
        String subject = TextFieldSubject.getText();

        Properties properties = new Properties();
        properties.put("mail.smtp.starttls.enable","true");
        properties.put("mail.smtp.EnableSSL.enable","true");
        properties.put("mail.smtp.host", "smtp.gmail.com");
        properties.put("mail.smtp.auth","true");
        properties.put("mail.debug", "true");
        properties.put("mail.smtp.host","smtp.gmail.com");
        properties.setProperty("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        properties.setProperty("mail.smtp.socketFactory.fallback", "false");
        properties.setProperty("mail.smtp.port", "465");
        properties.setProperty("mail.smtp.socketFactory.port", "465");

        Session session = Session.getDefaultInstance(properties, new javax.mail.Authenticator() {
            
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(fromEmail, fromEmailPassword);
            }
        });

        try{
            MimeMessage message = new  MimeMessage(session);
            message.setFrom(new InternetAddress(fromEmail));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(toEmail));
            message.setSubject(subject);
            message.setText(TextFieldMessage.getText());
            Transport.send(message);
        }
        catch(MessagingException ex){
            System.out.println(""+ex);
        }

        
      //
      //
        int stblassignedRequestlLegalOfficer.getSelectedRow();
       
        if(selectedRow <0){
        //JOptionPane.showMessageDialog(null,"Please select a row");
        JOptionPane.showMessageDialog(null, new JLabel(  "<html><h2><I>Please select<font color='red'> a row</font> from the<font color='green'> table</I></font></h2></html>"), "Warning", JOptionPane.WARNING_MESSAGE);
            
        }
        else{
        WorkRequest request = tblassignedRequestlLegalOfficer.getValueAt(selectedRow, 0);
       
            request.setStatus("Consent form sent");
            //request.setUserAccount(userAccount);
        //userAccount.getWorkQueue().getWorkRequestList().add(request);
        
        dB4OUtil.storeSystem(system);
        
        populateOrganisationpatientTable();
        populateLegalPatientTable();
        
        JOptionPane.showMessageDialog(null, new JLabel(  "<html><h2><I>Consent Form<font color='green'> sent</font> successfully!</I></font></h2></html>"),"Info", JOptionPane.INFORMATION_MESSAGE);
      
        //JOptionPane.showMessageDialog(null,"Consent Form Sent Successfully", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
        }
    }//GEN-LAST:event_jBtnConsentFormActionPerformed

    private void TextFieldToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldToActionPerformed

    private void TextFieldFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldFromActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldFrom;
    private javax.swing.JTextArea TextFieldMessage;
    private javax.swing.JTextField TextFieldSubject;
    private javax.swing.JTextField TextFieldTo;
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton jBtnConsentForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelConsentByDoctor;
    private javax.swing.JLabel jLabelFrom;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelSubject;
    private javax.swing.JLabel jLabelTo;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblPatientData;
    private javax.swing.JTable tblassignedRequest;
    // End of variables declaration//GEN-END:variables
}
