/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.committeEnterprise;
import HomePages.TableFormat;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import javax.mail.*;
//import javax.mail.internet.InternetAddress;/
//import javax.mail.internet.MimeMessage;


/**
 *
 * @author patol
 */
public class EncouragingPeopleJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CheckOldPatients
     */
    public EncouragingPeopleJPanel() {
        initComponents();
     
        tblRecoveredPeople.getTableHeader().setDefaultRenderer(new TableFormat());
        poppulateTable();
    }
    private void  poppulateTable(){
    
    
      DefaultTableModel dtmA = (DefaultTableModel)tblRecoveredPeople.getModel();
      dtmA.setRowCount(0);
      Object row[] = new Object[4];
       String line = "";  
       String splitBy = ",";  
        try   
        {  
            //parsing a CSV file into BufferedReader class constructor  
            BufferedReader br = new BufferedReader(new FileReader("CuredPatientsRecord.csv"));  
            while ((line = br.readLine()) != null)   //returns a Boolean value  
            {
            String[] csv = line.split(splitBy);    // use comma as separator 
            row[0]= csv[0];
            row[1]= csv[1];
            row[2]= csv[2];
            row[3]= csv[3];
            
            dtmA.addRow(row);
        }   }
            catch (IOException e)   
            {  e.printStackTrace(); }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecoveredPeople = new javax.swing.JTable();
        jLabelRecoveredPeople = new javax.swing.JLabel();
        jLabelTo = new javax.swing.JLabel();
        jLabelFrom = new javax.swing.JLabel();
        jLabelSubject = new javax.swing.JLabel();
        jLabelMessage = new javax.swing.JLabel();
        TextFieldTo = new javax.swing.JTextField();
        TextFieldFrom = new javax.swing.JTextField();
        TextFieldSubject = new javax.swing.JTextField();
        BtnSend = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jBtnMail = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextFieldMessage = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRecoveredPeople.setBackground(new java.awt.Color(0, 0, 0));
        tblRecoveredPeople.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        tblRecoveredPeople.setForeground(new java.awt.Color(255, 255, 255));
        tblRecoveredPeople.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Donor Name", "Email", "Covid Recovery Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRecoveredPeople.setGridColor(new java.awt.Color(0, 0, 0));
        tblRecoveredPeople.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblRecoveredPeople.setRowHeight(30);
        tblRecoveredPeople.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tblRecoveredPeople);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 137, 1240, 183));

        jLabelRecoveredPeople.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelRecoveredPeople.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRecoveredPeople.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRecoveredPeople.setText("Recovered People");
        add(jLabelRecoveredPeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 268, -1));

        jLabelTo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelTo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTo.setText("To:");
        add(jLabelTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        jLabelFrom.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelFrom.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFrom.setText("From:");
        add(jLabelFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, -1));

        jLabelSubject.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelSubject.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSubject.setText("Subject:");
        add(jLabelSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, -1, -1));

        jLabelMessage.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelMessage.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMessage.setText("Message:");
        add(jLabelMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, -1, -1));

        TextFieldTo.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldTo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        TextFieldTo.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldToActionPerformed(evt);
            }
        });
        add(TextFieldTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 330, -1));

        TextFieldFrom.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldFrom.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        TextFieldFrom.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldFrom.setText("aedprojecttitans@gmail.com");
        TextFieldFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldFromActionPerformed(evt);
            }
        });
        add(TextFieldFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 330, -1));

        TextFieldSubject.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldSubject.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        TextFieldSubject.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldSubject.setText("Plasma Donation Request");
        TextFieldSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldSubjectActionPerformed(evt);
            }
        });
        add(TextFieldSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 330, -1));

        BtnSend.setBackground(new java.awt.Color(31, 31, 31));
        BtnSend.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        BtnSend.setForeground(new java.awt.Color(255, 255, 255));
        BtnSend.setText("Send Mail");
        BtnSend.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSendActionPerformed(evt);
            }
        });
        add(BtnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 500, 110, 40));

        jPanel3.setBackground(new java.awt.Color(31, 31, 31));
        jPanel3.setPreferredSize(new java.awt.Dimension(926, 70));

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Kindly Donate Plasma for Needy ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 1606, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1630, -1));

        jBtnMail.setBackground(new java.awt.Color(31, 31, 31));
        jBtnMail.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jBtnMail.setForeground(new java.awt.Color(255, 255, 255));
        jBtnMail.setText(" Mail");
        jBtnMail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMailActionPerformed(evt);
            }
        });
        add(jBtnMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 130, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/letter.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 460, 140, 130));

        TextFieldMessage.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldMessage.setColumns(20);
        TextFieldMessage.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TextFieldMessage.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldMessage.setRows(5);
        TextFieldMessage.setText("Hello,\n\nGreetings of the Day!!\n\nSomeone is waiting for your kind anticipation.\nLots of patients from various blood group urgently require a plasma for covid 19 plasma therapy.\nKindly revert us if you could help us to serve patients.\n\n\nThanking You,\nPlasma Management team.\n");
        jScrollPane2.setViewportView(TextFieldMessage);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, 790, 260));
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldToActionPerformed

    private void TextFieldSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldSubjectActionPerformed

    private void BtnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSendActionPerformed
        // TODO add your handling code here:
        
        if(TextFieldTo.getText().equals("") || TextFieldSubject.getText().equals("")|| TextFieldMessage.getText().equals(""))
        {
        JOptionPane.showMessageDialog(null,new JLabel(  "<html><h2><I>All fields are</I><font color='red'> mandatory</font>!</h2></html>") , "Error", JOptionPane.ERROR_MESSAGE);
            
        }
        else{
        
//       System.out.println("Preparing to send message ..");
      
       String toEmail = TextFieldTo.getText();
//       String toEmail = "yashwant7kotipalli@gmail.com";
//       final String fromEmail = "yashwant7kotipalli@gmail.com";
       final String fromEmail = TextFieldFrom.getText();
       final String fromEmailPassword = "teamtitans"; //your email password
       String subject = TextFieldSubject.getText();
        
        Properties properties = new Properties();
        properties.put("mail.smtp.starttls.enable","true");
        properties.put("mail.smtp.EnableSSL.enable","true");
        properties.put("mail.smtp.host", "smtp.gmail.com"); 
        properties.put("mail.smtp.auth","true");
        properties.put("mail.debug", "true"); 
        properties.put("mail.smtp.host","smtp.gmail.com");
        properties.setProperty("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");   
        properties.setProperty("mail.smtp.socketFactory.fallback", "false");   
        properties.setProperty("mail.smtp.port", "465");   
        properties.setProperty("mail.smtp.socketFactory.port", "465"); 
        
        Session session = Session.getDefaultInstance(properties, new javax.mail.Authenticator() {
        protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication(fromEmail, fromEmailPassword);
        }
       });
        
        try{
          MimeMessage message = new  MimeMessage(session);
          message.setFrom(new InternetAddress(fromEmail));
          message.addRecipient(Message.RecipientType.TO, new InternetAddress(toEmail));
          message.setSubject(subject);
          message.setText(TextFieldMessage.getText());
          Transport.send(message);
        }
        catch(Exception ex){
            System.out.println(""+ex);
        }
        
  //      System.out.println("Sent message successfully ...");
        
     JOptionPane.showMessageDialog(null, new JLabel(  "<html><h2><I>Mail<font color='green'> sent</font> successfully!</I></h2></html>"));
        }          
       //JOptionPane.showMessageDialog(null,"Mail sent successfully!");
        
        
        
    }//GEN-LAST:event_BtnSendActionPerformed

    private void TextFieldFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldFromActionPerformed

    private void jBtnMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMailActionPerformed
        // TODO add your handling code here:
          int selectedRow = tblRecoveredPeople.getSelectedRow();
        if(selectedRow < 0){
            
             JOptionPane.showMessageDialog(null, new JLabel(  "<html><h2><I>Please select<font color='red'> a row</font> from the<font color='green'> table</font> to view the details!</I></h2></html>"), "Warning", JOptionPane.WARNING_MESSAGE);
           
            
            //JOptionPane.showMessageDialog(null,"Please select a row from the table first to View Details!","Warning!",JOptionPane.WARNING_MESSAGE);
        }
        else{
        
        
        TextFieldTo.setText(String.valueOf(tblRecoveredPeople.getValueAt(selectedRow, 2)));        
        
        }
        
        
    }//GEN-LAST:event_jBtnMailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSend;
    private javax.swing.JTextField TextFieldFrom;
    private javax.swing.JTextArea TextFieldMessage;
    private javax.swing.JTextField TextFieldSubject;
    private javax.swing.JTextField TextFieldTo;
    private javax.swing.JButton jBtnMail;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelFrom;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelRecoveredPeople;
    private javax.swing.JLabel jLabelSubject;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTo;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblRecoveredPeople;
    // End of variables declaration//GEN-END:variables
}
