/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.GovernmentFunding;

import Business.Account.Account;
import Business.ECOSystem;
import Business.Enterprise.Enterprise;
import Business.Person.VisitorDirectory;
import Business.WorkQueue.FundWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userInterface.AwarenessCamps.AwarenessCamps;
import userInterface.DoctorWorkArea.PatientTestRequestJPanel;

/**
 *
 * @author patol
 */
public class FundRequestStatusJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FundRequestStatusJPanel
     */
    
    ECOSystem system;
    JPanel rightPanel;
    VisitorDirectory vd = new VisitorDirectory();
    private Account userAccount;
    private Enterprise enterprise;
    
    public FundRequestStatusJPanel(JPanel rightPanel,Enterprise enterprise,Account userAccount) {
        initComponents();
        this.rightPanel = rightPanel;
        this.system = system;
        this.userAccount = userAccount;
        this.enterprise=enterprise;
        populateRequestTable();
        JTableWorkRequest.getTableHeader().setFont(new Font("Times New Roman" , Font.ITALIC,23));
    
    
    }
     public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) JTableWorkRequest.getModel();
        
        model.setRowCount(0);
        FundWorkRequest r = new FundWorkRequest();
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = ((FundWorkRequest) request).getEventName();
            row[1] = ((FundWorkRequest) request).getReceiver();
            row[2] = ((FundWorkRequest) request).getStatus();
            String result = String.valueOf(((FundWorkRequest) request).getFunds());
            row[3] = result;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTableWorkRequest = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        JTableWorkRequest.setBackground(new java.awt.Color(255, 204, 204));
        JTableWorkRequest.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        JTableWorkRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Event ", "Sender", "Status", "Funds"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTableWorkRequest);
        if (JTableWorkRequest.getColumnModel().getColumnCount() > 0) {
            JTableWorkRequest.getColumnModel().getColumn(0).setResizable(false);
            JTableWorkRequest.getColumnModel().getColumn(1).setResizable(false);
            JTableWorkRequest.getColumnModel().getColumn(2).setResizable(false);
            JTableWorkRequest.getColumnModel().getColumn(3).setResizable(false);
        }

        btnBack.setBackground(new java.awt.Color(153, 204, 255));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnBack)
                .addContainerGap(434, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        Component[] componentArray = rightPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AwarenessCamps dwjp = (AwarenessCamps) component;
        //dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableWorkRequest;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
